import { Contract } from './useContracts.types';

// Mock 데이터 — 온보딩용 빈 상태
export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'mock-1',
    business_id: 'biz-001',
    employer_user_key: 'mock-employer-key',
    worker_name: '박민수',
    worker_phone: '01011112222',
    contract_type: 'fullTime',
    status: 'draft',
    start_date: '2026-06-01',
    workplace: '강남구 논현동 123-4',
    job_description: '카페 매장 관리 및 고객 응대, 음료 제조',
    wage_type: 'monthly',
    base_wage: 2500000,
    wage_payment_date: '10',
    wage_payment_method: 'bankTransfer',
    work_days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    start_time: '09:00',
    end_time: '18:00',
    break_start_time: '12:00',
    break_end_time: '13:00',
    weekly_holiday: 'sun',
    paid_leave_clause: true,
    pension: true,
    health_insurance: true,
    employment_insurance: true,
    accident_insurance: true,
    social_insurance_clause: true,
    severance_clause: true,
    created_at: '2026-06-01T09:00:00Z',
    updated_at: '2026-06-01T09:00:00Z',
  },
  {
    id: 'mock-2',
    business_id: 'biz-002',
    employer_user_key: 'mock-employer-key',
    worker_user_key: 'mock-worker-key',
    worker_name: '김알바',
    worker_phone: '01098765432',
    contract_type: 'partTime',
    status: 'sent',
    start_date: '2026-05-20',
    workplace: '서초구 서초대로 77길 55',
    job_description: '주방 보조 및 설거지, 식자재 정리',
    wage_type: 'hourly',
    base_wage: 12000,
    wage_payment_date: '25',
    wage_payment_method: 'bankTransfer',
    work_days: ['tue', 'wed', 'thu', 'fri', 'sat'],
    start_time: '17:00',
    end_time: '22:00',
    break_start_time: '19:00',
    break_end_time: '19:30',
    weekly_holiday: 'mon',
    paid_leave_clause: false,
    pension: false,
    health_insurance: false,
    employment_insurance: false,
    accident_insurance: false,
    social_insurance_clause: false,
    severance_clause: false,
    created_at: '2026-06-20T14:30:00Z',
    updated_at: '2026-06-24T14:30:00Z',
  },
  {
    id: 'mock-3',
    business_id: 'biz-003',
    employer_user_key: 'mock-employer-key',
    worker_user_key: 'worker-user-3',
    worker_name: '이지은',
    worker_phone: '01033334444',
    contract_type: 'fixedTerm',
    status: 'viewed',
    start_date: '2026-04-10',
    workplace: '마포구 와우산로 94',
    job_description: '편집 디자인 및 SNS 콘텐츠 제작, 인쇄물 관리',
    wage_type: 'monthly',
    base_wage: 2200000,
    wage_payment_date: '5',
    wage_payment_method: 'bankTransfer',
    work_days: ['mon', 'tue', 'wed', 'thu'],
    start_time: '10:00',
    end_time: '19:00',
    break_start_time: '13:00',
    break_end_time: '14:00',
    weekly_holiday: 'fri',
    paid_leave_clause: true,
    pension: true,
    health_insurance: true,
    employment_insurance: true,
    accident_insurance: true,
    social_insurance_clause: true,
    severance_clause: false,
    created_at: '2026-04-10T09:00:00Z',
    updated_at: '2026-04-11T15:30:00Z',
  },
  {
    id: 'mock-4',
    business_id: 'biz-004',
    employer_user_key: 'mock-employer-key',
    worker_user_key: 'worker-user-4',
    worker_name: '최재훈',
    worker_phone: '01055556666',
    contract_type: 'fullTime',
    status: 'signed',
    start_date: '2026-03-02',
    workplace: '송파구 올림픽로 300 롯데월드타워 76층',
    job_description: '백엔드 개발 및 API 설계, 데이터베이스 운영 관리',
    wage_type: 'monthly',
    base_wage: 4500000,
    wage_payment_date: '25',
    wage_payment_method: 'bankTransfer',
    work_days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    start_time: '10:00',
    end_time: '19:00',
    break_start_time: '14:00',
    break_end_time: '15:00',
    weekly_holiday: 'sat,sun',
    paid_leave_clause: true,
    pension: true,
    health_insurance: true,
    employment_insurance: true,
    accident_insurance: true,
    social_insurance_clause: true,
    severance_clause: true,
    created_at: '2026-03-02T09:00:00Z',
    updated_at: '2026-03-03T11:00:00Z',
    employer_signature_data: '/signatures/employer_signature.jpg',
    worker_signature_data: '/signatures/worker_signature.jpg',
  },
  {
    id: 'mock-5',
    business_id: 'biz-005',
    employer_user_key: 'mock-employer-key',
    worker_user_key: 'worker-user-5',
    worker_name: '한소희',
    worker_phone: '01077778888',
    contract_type: 'fixedTerm',
    status: 'completed',
    start_date: '2025-12-01',
    workplace: '용산구 이태원로 27길 18',
    job_description: '영상 촬영 및 편집, 유튜브 채널 콘텐츠 기획·운영',
    wage_type: 'monthly',
    base_wage: 5000000,
    wage_payment_date: '15',
    wage_payment_method: 'bankTransfer',
    work_days: ['mon', 'wed', 'fri'],
    start_time: '13:00',
    end_time: '21:00',
    break_start_time: '17:00',
    break_end_time: '18:00',
    weekly_holiday: 'sat,sun',
    paid_leave_clause: false,
    pension: false,
    health_insurance: false,
    employment_insurance: false,
    accident_insurance: false,
    social_insurance_clause: false,
    severance_clause: false,
    created_at: '2025-12-01T09:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
    employer_signature_data: '/signatures/employer_signature.jpg',
    worker_signature_data: '/signatures/worker_signature.jpg',
  },
  {
    id: 'mock-6',
    business_id: 'biz-001',
    employer_user_key: 'mock-employer-key',
    worker_user_key: 'worker-user-6',
    worker_name: '고길동',
    worker_phone: '01012345678',
    contract_type: 'fullTime',
    status: 'cancelled',
    start_date: '2026-01-01',
    workplace: '서초구 서초대로 10',
    job_description: '시설 관리 및 고객 응대',
    wage_type: 'monthly',
    base_wage: 2800000,
    wage_payment_date: '15',
    wage_payment_method: 'bankTransfer',
    work_days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    start_time: '08:00',
    end_time: '17:00',
    break_start_time: '12:00',
    break_end_time: '13:00',
    weekly_holiday: 'sun',
    paid_leave_clause: true,
    pension: true,
    health_insurance: true,
    employment_insurance: true,
    accident_insurance: true,
    social_insurance_clause: true,
    severance_clause: true,
    created_at: '2025-12-20T09:00:00Z',
    updated_at: '2026-01-05T10:00:00Z',
  },
  {
    id: 'mock-7',
    business_id: 'biz-001',
    employer_user_key: 'mock-employer-key',
    worker_user_key: 'worker-user-7',
    worker_name: '오영심',
    worker_phone: '01099990000',
    contract_type: 'partTime',
    status: 'expired',
    start_date: '2026-02-01',
    workplace: '강남구 테헤란로 123',
    job_description: '홀 서빙 및 캐셔',
    wage_type: 'hourly',
    base_wage: 15000,
    wage_payment_date: '20',
    wage_payment_method: 'bankTransfer',
    work_days: ['sat', 'sun'],
    start_time: '10:00',
    end_time: '15:00',
    break_start_time: '12:00',
    break_end_time: '12:30',
    weekly_holiday: '',
    paid_leave_clause: false,
    pension: false,
    health_insurance: false,
    employment_insurance: false,
    accident_insurance: true,
    social_insurance_clause: false,
    severance_clause: false,
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'mock-8',
    business_id: 'biz-001',
    employer_user_key: 'mock-employer-key',
    worker_user_key: 'worker-user-8',
    worker_name: '고등학생',
    worker_phone: '01012345678',
    contract_type: 'partTime',
    status: 'signed',
    start_date: '2026-07-01',
    workplace: '강남구 논현동 123-4',
    job_description: '홀 서빙 및 매장 청소',
    wage_type: 'hourly',
    base_wage: 10000,
    wage_payment_date: '10',
    wage_payment_method: 'bankTransfer',
    work_days: ['sat', 'sun'],
    start_time: '12:00',
    end_time: '18:00',
    break_start_time: '14:00',
    break_end_time: '14:30',
    weekly_holiday: '',
    paid_leave_clause: false,
    pension: false,
    health_insurance: false,
    employment_insurance: false,
    accident_insurance: true,
    social_insurance_clause: false,
    severance_clause: false,
    worker_birth_date: '2009-05-05',
    is_minor: true,
    is_young_worker: true,
    doc_parent_consent_status: 'required',
    doc_family_cert_status: 'required',
    doc_employment_permit_status: 'not_required',
    employer_signature_data: '/signatures/employer_signature.jpg',
    worker_signature_data: '/signatures/worker_signature.jpg',
    employer_signed_at: '2026-06-25T09:00:00Z',
    worker_signed_at: '2026-06-25T10:00:00Z',
    created_at: '2026-06-24T09:00:00Z',
    updated_at: '2026-06-25T10:00:00Z',
  },
  {
    id: 'mock-template-1',
    business_id: 'biz-001',
    employer_user_key: 'mock-employer-key',
    worker_name: '',
    worker_phone: '',
    contract_type: 'partTime',
    status: 'template',
    template_name: '주말 홀 서빙 알바 양식',
    start_date: '',
    workplace: '강남구 논현동 123-4',
    job_description: '홀 서빙 및 테이블 정리, 매장 청소',
    wage_type: 'hourly',
    base_wage: 12000,
    wage_payment_date: '15',
    wage_payment_method: 'bankTransfer',
    work_days: ['sat', 'sun'],
    start_time: '11:00',
    end_time: '20:00',
    break_start_time: '15:00',
    break_end_time: '16:00',
    weekly_holiday: '',
    paid_leave_clause: false,
    pension: false,
    health_insurance: false,
    employment_insurance: false,
    accident_insurance: true,
    social_insurance_clause: false,
    severance_clause: false,
    created_at: '2026-07-02T04:45:00Z',
    updated_at: '2026-07-02T04:45:00Z',
  },
  {
    id: 'mock-template-2',
    business_id: 'biz-001',
    employer_user_key: 'mock-employer-key',
    worker_name: '',
    worker_phone: '',
    contract_type: 'fullTime',
    status: 'template',
    template_name: '평일 정규직 바리스타',
    start_date: '',
    workplace: '강남구 논현동 123-4',
    job_description: '커피 제조, 고객 응대 및 매장 전반 관리',
    wage_type: 'monthly',
    base_wage: 2500000,
    wage_payment_date: '10',
    wage_payment_method: 'bankTransfer',
    work_days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    start_time: '08:00',
    end_time: '17:00',
    break_start_time: '12:00',
    break_end_time: '13:00',
    weekly_holiday: 'sun',
    paid_leave_clause: true,
    pension: true,
    health_insurance: true,
    employment_insurance: true,
    accident_insurance: true,
    social_insurance_clause: true,
    severance_clause: true,
    created_at: '2026-07-02T04:45:00Z',
    updated_at: '2026-07-02T04:45:00Z',
  },
  {
    id: 'mock-template-3',
    business_id: 'biz-001',
    employer_user_key: 'mock-employer-key',
    worker_name: '',
    worker_phone: '',
    contract_type: 'fixedTerm',
    status: 'template',
    template_name: '단기 행사 스태프',
    start_date: '',
    workplace: '코엑스 전시관',
    job_description: '행사장 안내, 부스 보조 및 동선 안내',
    wage_type: 'daily',
    base_wage: 100000,
    wage_payment_date: '말일',
    wage_payment_method: 'bankTransfer',
    work_days: ['fri', 'sat', 'sun'],
    start_time: '09:00',
    end_time: '18:00',
    break_start_time: '13:00',
    break_end_time: '14:00',
    weekly_holiday: '',
    paid_leave_clause: false,
    pension: false,
    health_insurance: false,
    employment_insurance: false,
    accident_insurance: true,
    social_insurance_clause: false,
    severance_clause: false,
    created_at: '2026-07-02T04:45:00Z',
    updated_at: '2026-07-02T04:45:00Z',
  },
];

import { generatePrintableHTML } from '../domain/contract/template';

// 근로계약서 HTML 생성 헬퍼 (Mock 모드용 — template.ts로 단일화)
export function generateContractHtml(contract: Contract): string {
  return generatePrintableHTML(contract);
}
